// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm2VxhzeXbSZ1gmhPBLYP9zKqgXzIl-iE',
    appId: '1:301239858960:web:a025d0b66cd61a91045795',
    messagingSenderId: '301239858960',
    projectId: 'khaboki-ed91f',
    authDomain: 'khaboki-ed91f.firebaseapp.com',
    storageBucket: 'khaboki-ed91f.appspot.com',
    measurementId: 'G-JERFPYZNT0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATNXamUO56iYsGzYhKGBnBRDgMTmyWGKk',
    appId: '1:301239858960:android:2f7aeb494c8996a4045795',
    messagingSenderId: '301239858960',
    projectId: 'khaboki-ed91f',
    storageBucket: 'khaboki-ed91f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVS22RGYqGO4_pjdg3Sn1EQ7hvdzVf7zU',
    appId: '1:301239858960:ios:0619e54e4ff6b0e8045795',
    messagingSenderId: '301239858960',
    projectId: 'khaboki-ed91f',
    storageBucket: 'khaboki-ed91f.appspot.com',
    iosBundleId: 'com.example.projecrFoodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVS22RGYqGO4_pjdg3Sn1EQ7hvdzVf7zU',
    appId: '1:301239858960:ios:0619e54e4ff6b0e8045795',
    messagingSenderId: '301239858960',
    projectId: 'khaboki-ed91f',
    storageBucket: 'khaboki-ed91f.appspot.com',
    iosBundleId: 'com.example.projecrFoodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCm2VxhzeXbSZ1gmhPBLYP9zKqgXzIl-iE',
    appId: '1:301239858960:web:3fc776d5e4c138c0045795',
    messagingSenderId: '301239858960',
    projectId: 'khaboki-ed91f',
    authDomain: 'khaboki-ed91f.firebaseapp.com',
    storageBucket: 'khaboki-ed91f.appspot.com',
    measurementId: 'G-WJNNF0VY13',
  );
}
